
import { Navbar } from "@/components/Navbar/Navbar";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { Toaster } from "react-hot-toast";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Toaster position="top-right" />
       

      </body>


    </html>
    </AuthProvider>
  );
}
